### ISSUE TITLE
Talk Balloons being updated.

### ISSUE THREAD

**Issue by SilentCrossSip** [CERBON-MODS/Talk-Balloons#2]
- [x] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of Talk Balloons mod**
- [x] **I have checked the [FAQ](https://github.com/CERBON-MODS/Talk-Balloons/blob/master/FAQ.md) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/CERBON-MODS/Talk-Balloons/blob/master/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/CERBON-MODS/Talk-Balloons/blob/master/CODE_OF_CONDUCT.md)**

Could Talk Balloons be updated and actually work alongside the Cerebon Api and updated to newer versions, as this mod is rlly essential to another mod that i am trying to use (UnityTranslate) and would also like to see if this can be fixed for the benefit of others aswell. (Talk balloons have not been really working with Fabric and Cerebon Api at all)

**Comment by BluSpring** [comment]
Hello, I've now been made the maintainer of Talk Balloons, and it now no longer relies on CERBON's API.
As such, Talk Balloons has now been officially updated all the way to 1.21.4 with support for LexForge, NeoForge, and Fabric.
